# Pandas
#### Data structures in Pandas
        - Pandas Series Object (Series):
               Data having single column (only 1 feature)
        - Pandas Dataframe Object (Dataframe):
               Data having more than one column will be dataframe

In [1]:
import pandas as pd

# Series

In [14]:
# A series with default indices (integer indices)

In [15]:
s1 = pd.Series([12,23,45,43,54,22,70,98])

In [16]:
s1

0    12
1    23
2    45
3    43
4    54
5    22
6    70
7    98
dtype: int64

In [17]:
s1.values

array([12, 23, 45, 43, 54, 22, 70, 98])

In [18]:
s1.index

RangeIndex(start=0, stop=8, step=1)

In [19]:
s1.dtype

dtype('int64')

In [20]:
# A series with customized indices (Labels) (label indices)

In [21]:
s2 = pd.Series([12,23,45,43,54,22,70,98],index=['apple','banana','orange','guava','mango','grapes','peeches','cherries'])

In [22]:
s2

apple       12
banana      23
orange      45
guava       43
mango       54
grapes      22
peeches     70
cherries    98
dtype: int64

### Indexing and Slicing

In [29]:
s1

0    12
1    23
2    45
3    43
4    54
5    22
6    70
7    98
dtype: int64

In [30]:
s1[5]

np.int64(22)

In [31]:
s1[3:7]

3    43
4    54
5    22
6    70
dtype: int64

In [32]:
s2['banana']

np.int64(23)

In [33]:
s2['orange':'cherries']

orange      45
guava       43
mango       54
grapes      22
peeches     70
cherries    98
dtype: int64

# Data Frame

In [38]:
df = pd.DataFrame({
    'Rollno' : [1,2,3,4,5,6,7,8],
    'Name' : ['Zaeem','Husain','Ali','Omer','Arquam','Abdullah','Haris','Hamza'],
    'DSAmarks' : [98,93,39,48,49,29,40,29]
})

In [39]:
df

   Rollno      Name  DSAmarks
0       1     Zaeem        98
1       2    Husain        93
2       3       Ali        39
3       4      Omer        48
4       5    Arquam        49
5       6  Abdullah        29
6       7     Haris        40
7       8     Hamza        29

# Data Loading

In [47]:
empD = pd.read_excel('employee_data.xlsx')
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [48]:
empD.shape

(35, 9)

In [53]:
empD.head()

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645

In [54]:
empD.tail()

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [55]:
empD.sample(6)

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608

In [56]:
empD.columns

Index(['First Name', 'Last Name', 'Gender', 'Age', 'Salary', 'Expenditure',
       'Savings', 'Expenditure Percentage', 'Savings Percentage'],
      dtype='str')

In [57]:
empD.index

RangeIndex(start=0, stop=35, step=1)

### Working with Columns
     - select col
     - delete
     - update
     - create new col from old col
     - merge cols
     - splits

#### Selecting a single column

In [61]:
empD['Last Name']

0       Mishra
1        Singh
2       Thakur
3         Kaur
4     Deshmukh
5          Das
6        Bhatt
7          Rao
8        Mehta
9        Patel
10      Mishra
11       Verma
12       Joshi
13       Patel
14     Acharya
15        Kaur
16       Kumar
17       Yadav
18         Das
19       Patil
20        Shah
21       Patil
22      Sharma
23       Yadav
24      Sharma
25       Gupta
26      Kumari
27    Kulkarni
28        Shah
29       Joshi
30      Pandey
31       Gupta
32      Khatri
33     Agarwal
34     Agarwal
Name: Last Name, dtype: str

#### Selecting multiple Column

In [63]:
empD[['First Name','Salary','Savings']]

   First Name  Salary  Savings
0      Aditi    80000    15000
1        Sona   70000    12000
2        Devi   65000     5000
3      Anjali   62000    12000
4       Sahil   62000     5000
5      Adhira   62000     3000
6       Divya   52500     5500
7        Amar   52100     6100
8        Jaya   52000     6000
9       Candy   52000    12000
10     Sudhir   52000     5000
11     Raghav   51000     2000
12    Amitabh   51000     1000
13      Kanak   50500    10500
14      Tulsi   45200     5200
15    Jasleen   45000     5000
16        Nil   42000     4000
17      Anand   42000     4000
18    Atharva   41000     6000
19      Charu   40000     5000
20       Ajay   36000     4000
21        Jai   35500     5500
22    Ishaan    35000    10000
23     Dhruva   35000    13000
24      Artha   35000     4000
25     Shaila   35000     1000
26      Inaya   30000    10000
27      Darsh   30000     2000
28      Mihir   30000     2000
29    Agastya   25500     5500
30      Shaan   25200     3200
31      Navi    25000     5000
32      Ambar   25000     3000
33      Lata    25000     1000
34      Anaya   24100     3100

#### adding new column

In [64]:
empD['tax%'] = 15
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,15
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,15
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,15
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,15
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,15
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,15
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,15
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,15
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,15
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,15
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,15
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,15
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,15
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,15
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,15
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,15
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,15
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,15
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,15
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,15
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,15
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,15
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,15
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,15
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,15
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,15
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,15
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,15
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,15
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,15
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,15
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,15
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,15
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,15
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,15

In [65]:
def decide_tax_percentage(sal):
    if sal >= 200000:
        return 20
    elif sal >= 150000:
        return 15
    elif sal >= 100000:
        return 10
    else:
        return 5

In [67]:
empD['tax%'] = empD.Salary.apply(decide_tax_percentage)

In [68]:
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,5
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,5
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,5
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,5
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,5
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,5
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,5
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,5
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,5
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,5
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,5
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,5
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,5
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,5
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,5
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,5
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,5
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,5
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,5
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,5
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,5
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,5
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,5
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,5
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,5
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,5
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,5
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,5
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,5
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,5
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,5
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,5
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,5
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,5
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,5

In [74]:
empD.Salary.apply(lambda x:20 if x>=75000 else 15 if x>=50000 else 10 if x>=25000 else 5)

0     20
1     15
2     15
3     15
4     15
5     15
6     15
7     15
8     15
9     15
10    15
11    15
12    15
13    15
14    10
15    10
16    10
17    10
18    10
19    10
20    10
21    10
22    10
23    10
24    10
25    10
26    10
27    10
28    10
29    10
30    10
31    10
32    10
33    10
34     5
Name: Salary, dtype: int64

In [75]:
empD['tax%'] = empD.Salary.apply(lambda x:20 if x>=75000 else 15 if x>=50000 else 10 if x>=25000 else 5)

In [76]:
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,15
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,15
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,15
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,15
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,15
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,15
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,15
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,15
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,15
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,15
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,15
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,15
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,15
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,10
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,10
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,10
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,10
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,10
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,10
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,5

In [77]:
empD['tax_amount'] = empD.Salary.apply(lambda x: x*.20 if x>=75000 else x*.15 if x>=50000 else x*.10 if x>=25000 else x*.05)

In [78]:
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%,tax_amount
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20,16000.0
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,15,10500.0
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,15,9750.0
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,15,9300.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,15,9300.0
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,15,9300.0
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,15,7875.0
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,15,7815.0
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,15,7800.0
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,15,7800.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,15,7800.0
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,15,7650.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,15,7650.0
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,15,7575.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,10,4520.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,10,4500.0
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,10,4200.0
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,10,4200.0
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,10,4100.0
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,10,4000.0
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10,3600.0
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10,3550.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10,3500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10,3500.0
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10,3500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10,3500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10,3000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10,3000.0
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10,3000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10,2550.0
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10,2520.0
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10,2500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10,2500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10,2500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,5,1205.0

In [79]:
empD['net'] = empD['Salary'] - empD['tax_amount']
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage,tax%,tax_amount,net
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500,20,16000.0,64000.0
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429,15,10500.0,59500.0
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923,15,9750.0,55250.0
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548,15,9300.0,52700.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645,15,9300.0,52700.0
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387,15,9300.0,52700.0
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762,15,7875.0,44625.0
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083,15,7815.0,44285.0
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385,15,7800.0,44200.0
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769,15,7800.0,44200.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154,15,7800.0,44200.0
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216,15,7650.0,43350.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608,15,7650.0,43350.0
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921,15,7575.0,42925.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044,10,4520.0,40680.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111,10,4500.0,40500.0
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238,10,4200.0,37800.0
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238,10,4200.0,37800.0
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341,10,4100.0,36900.0
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000,10,4000.0,36000.0
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111,10,3600.0,32400.0
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930,10,3550.0,31950.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714,10,3500.0,31500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429,10,3500.0,31500.0
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286,10,3500.0,31500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571,10,3500.0,31500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333,10,3000.0,27000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667,10,3000.0,27000.0
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667,10,3000.0,27000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686,10,2550.0,22950.0
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984,10,2520.0,22680.0
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000,10,2500.0,22500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000,10,2500.0,22500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000,10,2500.0,22500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631,5,1205.0,22895.0

#### Deleting a Column

In [84]:
del empD['Savings Percentage']

In [85]:
empD

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,tax%,tax_amount,net
0,Aditi,Mishra,Female,35,80000,65000,15000,20,16000.0,64000.0
1,Sona,Singh,Female,35,70000,58000,12000,15,10500.0,59500.0
2,Devi,Thakur,Female,36,65000,60000,5000,15,9750.0,55250.0
3,Anjali,Kaur,Female,42,62000,50000,12000,15,9300.0,52700.0
4,Sahil,Deshmukh,Male,29,62000,57000,5000,15,9300.0,52700.0
5,Adhira,Das,Male,42,62000,59000,3000,15,9300.0,52700.0
6,Divya,Bhatt,Female,42,52500,47000,5500,15,7875.0,44625.0
7,Amar,Rao,Male,52,52100,46000,6100,15,7815.0,44285.0
8,Jaya,Mehta,Female,28,52000,46000,6000,15,7800.0,44200.0
9,Candy,Patel,Female,35,52000,40000,12000,15,7800.0,44200.0
10,Sudhir,Mishra,Male,35,52000,47000,5000,15,7800.0,44200.0
11,Raghav,Verma,Male,28,51000,49000,2000,15,7650.0,43350.0
12,Amitabh,Joshi,Male,36,51000,50000,1000,15,7650.0,43350.0
13,Kanak,Patel,Male,45,50500,40000,10500,15,7575.0,42925.0
14,Tulsi,Acharya,Female,40,45200,40000,5200,10,4520.0,40680.0
15,Jasleen,Kaur,Female,50,45000,40000,5000,10,4500.0,40500.0
16,Nil,Kumar,Male,44,42000,38000,4000,10,4200.0,37800.0
17,Anand,Yadav,Male,28,42000,38000,4000,10,4200.0,37800.0
18,Atharva,Das,Male,29,41000,35000,6000,10,4100.0,36900.0
19,Charu,Patil,Female,26,40000,35000,5000,10,4000.0,36000.0
20,Ajay,Shah,Male,35,36000,32000,4000,10,3600.0,32400.0
21,Jai,Patil,Male,36,35500,30000,5500,10,3550.0,31950.0
22,Ishaan,Sharma,Male,35,35000,25000,10000,10,3500.0,31500.0
23,Dhruva,Yadav,Male,42,35000,22000,13000,10,3500.0,31500.0
24,Artha,Sharma,Male,31,35000,31000,4000,10,3500.0,31500.0
25,Shaila,Gupta,Female,51,35000,34000,1000,10,3500.0,31500.0
26,Inaya,Kumari,Female,52,30000,20000,10000,10,3000.0,27000.0
27,Darsh,Kulkarni,Male,41,30000,28000,2000,10,3000.0,27000.0
28,Mihir,Shah,Male,30,30000,28000,2000,10,3000.0,27000.0
29,Agastya,Joshi,Male,50,25500,20000,5500,10,2550.0,22950.0
30,Shaan,Pandey,Male,37,25200,22000,3200,10,2520.0,22680.0
31,Navi,Gupta,Female,51,25000,20000,5000,10,2500.0,22500.0
32,Ambar,Khatri,Male,36,25000,22000,3000,10,2500.0,22500.0
33,Lata,Agarwal,Female,28,25000,24000,1000,10,2500.0,22500.0
34,Anaya,Agarwal,Female,25,24100,21000,3100,5,1205.0,22895.0

# Working with Rows and Columns

In [3]:
emp = pd.read_excel('employee_data.xlsx')
emp

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
4,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769
10,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154
11,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216
12,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
17,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238
18,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000
20,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111
21,Jai,Patil,Male,36,35500,30000,5500,0.845070,0.154930
22,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
24,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667
28,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686
30,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000
32,Ambar,Khatri,Male,36,25000,22000,3000,0.880000,0.120000
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [4]:
emp.iloc[4:8,0:4]

  First Name Last Name  Gender  Age
4      Sahil  Deshmukh    Male   29
5     Adhira       Das    Male   42
6      Divya     Bhatt  Female   42
7       Amar       Rao    Male   52

In [5]:
emp.loc[4:7, 'Gender':'Expenditure Percentage']

   Gender  Age  Salary  Expenditure  Savings  Expenditure Percentage
4    Male   29   62000        57000     5000                0.919355
5    Male   42   62000        59000     3000                0.951613
6  Female   42   52500        47000     5500                0.895238
7    Male   52   52100        46000     6100                0.882917

In [8]:
emp1 = pd.read_excel('employee_data.xlsx',header=None)
emp1

,0,1,2,3,4,5,6,7,8
0,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
1,Aditi,Mishra,Female,35,80000,65000,15000,0.8125,0.1875
2,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
3,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
4,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
5,Sahil,Deshmukh,Male,29,62000,57000,5000,0.919355,0.080645
6,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
7,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762
8,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
9,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385
10,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769
11,Sudhir,Mishra,Male,35,52000,47000,5000,0.903846,0.096154
12,Raghav,Verma,Male,28,51000,49000,2000,0.960784,0.039216
13,Amitabh,Joshi,Male,36,51000,50000,1000,0.980392,0.019608
14,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
15,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044
16,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
17,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
18,Anand,Yadav,Male,28,42000,38000,4000,0.904762,0.095238
19,Atharva,Das,Male,29,41000,35000,6000,0.853659,0.146341
20,Charu,Patil,Female,26,40000,35000,5000,0.875,0.125
21,Ajay,Shah,Male,35,36000,32000,4000,0.888889,0.111111
22,Jai,Patil,Male,36,35500,30000,5500,0.84507,0.15493
23,Ishaan,Sharma,Male,35,35000,25000,10000,0.714286,0.285714
24,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
25,Artha,Sharma,Male,31,35000,31000,4000,0.885714,0.114286
26,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
27,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333
28,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667
29,Mihir,Shah,Male,30,30000,28000,2000,0.933333,0.066667
30,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686
31,Shaan,Pandey,Male,37,25200,22000,3200,0.873016,0.126984
32,Navi,Gupta,Female,51,25000,20000,5000,0.8,0.2
33,Ambar,Khatri,Male,36,25000,22000,3000,0.88,0.12
34,Lata,Agarwal,Female,28,25000,24000,1000,0.96,0.04
35,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [9]:
emp1.head()

,0,1,2,3,4,5,6,7,8
0,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
1,Aditi,Mishra,Female,35,80000,65000,15000,0.8125,0.1875
2,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
3,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
4,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548

In [12]:
emp1.iloc[1:7,3:8]

    3      4      5      6         7
1  35  80000  65000  15000    0.8125
2  35  70000  58000  12000  0.828571
3  36  65000  60000   5000  0.923077
4  42  62000  50000  12000  0.806452
5  29  62000  57000   5000  0.919355
6  42  62000  59000   3000  0.951613

In [14]:
emp[emp.Gender=='Female']

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
0,Aditi,Mishra,Female,35,80000,65000,15000,0.812500,0.187500
1,Sona,Singh,Female,35,70000,58000,12000,0.828571,0.171429
2,Devi,Thakur,Female,36,65000,60000,5000,0.923077,0.076923
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762
8,Jaya,Mehta,Female,28,52000,46000,6000,0.884615,0.115385
9,Candy,Patel,Female,35,52000,40000,12000,0.769231,0.230769
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
19,Charu,Patil,Female,26,40000,35000,5000,0.875000,0.125000
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000
33,Lata,Agarwal,Female,28,25000,24000,1000,0.960000,0.040000
34,Anaya,Agarwal,Female,25,24100,21000,3100,0.871369,0.128631

In [15]:
emp[emp.Age>=40]

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
3,Anjali,Kaur,Female,42,62000,50000,12000,0.806452,0.193548
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
6,Divya,Bhatt,Female,42,52500,47000,5500,0.895238,0.104762
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
14,Tulsi,Acharya,Female,40,45200,40000,5200,0.884956,0.115044
15,Jasleen,Kaur,Female,50,45000,40000,5000,0.888889,0.111111
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
25,Shaila,Gupta,Female,51,35000,34000,1000,0.971429,0.028571
26,Inaya,Kumari,Female,52,30000,20000,10000,0.666667,0.333333
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686
31,Navi,Gupta,Female,51,25000,20000,5000,0.800000,0.200000

In [18]:
emp[(emp.Age>40) & (emp.Gender=='Male')]

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238
23,Dhruva,Yadav,Male,42,35000,22000,13000,0.628571,0.371429
27,Darsh,Kulkarni,Male,41,30000,28000,2000,0.933333,0.066667
29,Agastya,Joshi,Male,50,25500,20000,5500,0.784314,0.215686

In [4]:
emp[(emp.Age>40)&(emp.Gender=='Male')&(emp.Salary>40000)]

,First Name,Last Name,Gender,Age,Salary,Expenditure,Savings,Expenditure Percentage,Savings Percentage
5,Adhira,Das,Male,42,62000,59000,3000,0.951613,0.048387
7,Amar,Rao,Male,52,52100,46000,6100,0.882917,0.117083
13,Kanak,Patel,Male,45,50500,40000,10500,0.792079,0.207921
16,Nil,Kumar,Male,44,42000,38000,4000,0.904762,0.095238

In [2]:
data = pd.read_csv('student_marks.csv')

In [8]:
data

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
6,pooja,F,04-05-1987,55,64,61,58,75,58,64,61
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77

In [10]:
data[(data.Maths>50) & (data.Gender=='M')]

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87
9,Mukesh,M,02-09-1989,96,46,77,83,58,83,46,77

In [22]:
data[data.DOB.str.contains('08')][['Unnamed: 0','Gender']]

  Unnamed: 0 Gender
3    Jessica      F
8      Farha      F

In [24]:
data.Gender.unique()

<ArrowStringArray>
['M', 'F']
Length: 2, dtype: str

In [25]:
data.Gender.value_counts()

Gender
M    5
F    5
Name: count, dtype: int64

In [3]:
data.head()

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
0,John,M,05-04-1988,55,45,56,87,21,52,89,65
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53

In [4]:
data[data.Physics > data.Physics.mean()]

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
1,Suresh,M,04-05-1987,75,96,78,64,90,61,58,2
3,Jessica,F,12-08-1990,78,96,86,63,54,89,75,45
4,Jennifer,F,02-09-1989,58,96,78,46,96,77,83,53
5,Annu,F,05-04-1988,45,87,52,89,55,89,87,52
7,Ritesh,M,25-05-1989,54,76,87,56,25,56,76,87

In [9]:
data[data.Chemistry == data.Chemistry.max()]

,Unnamed: 0,Gender,DOB,Maths,Physics,Chemistry,English,Biology,Economics,History,Civics
2,Ramesh,M,25-05-1989,25,54,89,76,95,87,56,74
8,Farha,F,12-08-1990,55,63,89,75,78,75,63,89

In [10]:
movies = pd.read_csv("datalab_export_2026-10-17 13_39_34.csv")

In [11]:
movies

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
95,s96,TV Show,The Circle,NaN,Michelle Buteau,"United States, United Kingdom","September 8, 2021",2021,TV-MA,3 Seasons,Reality TV,Status and strategy collide in this social exp...
96,s97,Movie,If I Leave Here Tomorrow: A Film About Lynyrd ...,Stephen Kijak,"Ronnie Van Zandt, Gary Rossington, Allen Colli...",United States,"September 7, 2021",2018,TV-MA,97 min,"Documentaries, Music & Musicals","Using interviews and archival footage, this do..."
97,s98,TV Show,Kid Cosmic,NaN,"Jack Fisher, Tom Kenny, Amanda C. Miller, Kim ...",United States,"September 7, 2021",2021,TV-Y7,2 Seasons,"Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",A boy's superhero dreams come true when he fin...
98,s99,TV Show,Octonauts: Above & Beyond,NaN,"Antonio Aakeel, Chipo Chung, Simon Foster, Ter...",United Kingdom,"September 7, 2021",2021,TV-Y,1 Season,"British TV Shows, Kids' TV",The Octonauts expand their exploration beyond ...
99,s100,TV Show,On the Verge,NaN,"Julie Delpy, Elisabeth Shue, Sarah Jones, Alex...","France, United States","September 7, 2021",2021,TV-MA,1 Season,"TV Comedies, TV Dramas","Four women — a chef, a single mom, an heiress ..."

In [12]:
movies.shape

(100, 12)

In [ ]:
movies